In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr1.shape

(5,)

In [5]:
arr1.size

5

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim

1

In [10]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2.shape

(2, 3)

In [12]:
type(arr2)

numpy.ndarray

In [13]:
arr2.dtype

dtype('int64')

In [14]:
arr2.size

6

In [15]:
arr2.ndim

2

In [16]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
arr3.shape

(1, 3, 3)